apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-crm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-crm
  template:
    metadata:
      labels:
        app: django-crm
    spec:
      containers:
      - name: django-crm
        image: django-crm:latest
        imagePullPolicy: Never    # Add this line
        ports:
        - containerPort: 8000