version: '3'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=ubuntu
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - odoo-network
    ports:
      - "5433:5432"

  odoo:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    volumes:
      - ../odoo.conf:/opt/odoo/odoo18_v1/odoo.conf:ro
      - ../:/opt/odoo/odoo18_v1:ro
      - odoo-data:/var/lib/odoo
      - odoo-logs:/var/log/odoo
      - ../addons:/mnt/extra-addons
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=ubuntu
      - DB_PASSWORD=admin
    ports:
      - "8069:8069"
      - "8072:8072"
    networks:
      - odoo-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/odoo.conf:/etc/nginx/conf.d/default.conf:ro  # Changed this line
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - odoo
    networks:
      - odoo-network

networks:
  odoo-network:

volumes:
  odoo-db-data:
  odoo-data:
  odoo-logs: