version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=ubuntu
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - odoo-network
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ubuntu -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  odoo:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - odoo-config:/opt/odoo/odoo18_v1/config
      - ../odoo.conf:/opt/odoo/odoo18_v1/config/odoo.conf:ro
      - odoo-data:/var/lib/odoo
      - ../addons:/mnt/extra-addons:ro
    environment:
      - HOST=db
      - PORT=5432
      - USER=ubuntu
      - PASSWORD=admin
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=ubuntu
      - DB_PASSWORD=admin
      - DB_SSLMODE=disable
      - PYTHONOPTIMIZE=2
      - LANG=C.UTF-8
      - TZ=UTC
    command: [
      "/opt/odoo/odoo18_v1/odoo-bin",
      "--config=/opt/odoo/odoo18_v1/config/odoo.conf",
      "--log-level=info",
      "--workers=2",
      "--max-cron-threads=1",
      "--logfile=",
      "--log-handler=:INFO"
    ]
    ports:
      - "8069:8069"
      - "8072:8072"
    networks:
      - odoo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069/web/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/odoo.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx
      - nginx-cache:/var/cache/nginx
    depends_on:
      - odoo
    networks:
      - odoo-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  odoo-network:
    driver: bridge

volumes:
  odoo-db-data:
  odoo-data:
  odoo-config:
  nginx-cache: