name: Deploy to Odoo Server

on:
  push:
    branches:
      - master  # or your main branch name
    paths:
      - 'docker/**'
      - 'addons/**'
      - '.github/workflows/**'
      - 'odoo.conf'
      - 'requirements.txt'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          SERVER_USER: ubuntu
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          DEPLOY_PATH: /home/ubuntu/odoo_projects/odoo18_v1
        run: |
          # Copy files to server
          scp -r docker/* $SERVER_USER@$SERVER_HOST:$DEPLOY_PATH/docker/
          scp -r addons/* $SERVER_USER@$SERVER_HOST:$DEPLOY_PATH/addons/
          scp odoo.conf $SERVER_USER@$SERVER_HOST:$DEPLOY_PATH/
          scp requirements.txt $SERVER_USER@$SERVER_HOST:$DEPLOY_PATH/


          # SSH into server and restart containers
          ssh $SERVER_USER@$SERVER_HOST "cd $DEPLOY_PATH && \
            docker-compose -f docker/docker-compose.yml down && \
            docker-compose -f docker/docker-compose.yml up -d --build"

      - name: Verify deployment
        run: |
          # Wait for services to start
          sleep 30

          # Check if the services are running
          ssh ubuntu@${{ secrets.SERVER_HOST }} "cd $DEPLOY_PATH && \
            docker-compose -f docker/docker-compose.yml ps && \
            echo 'Deployment status check completed'"
